create table if not exists public.coach_messages (
  id bigint generated by default as identity primary key,
  session_id text not null,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  detected_entity text,
  detected_intent text,
  created_at timestamptz not null default now()
);

create index if not exists idx_coach_messages_session_created
  on public.coach_messages (session_id, created_at);
