-- Akro du Foot - Hall of Fame 100+ vague 1.
-- Seed additif et relançable : ajoute 70 légendes au socle des 30 déjà validées.
-- Ne supprime rien, ne vide rien et ne remplace jamais une donnée fiable par du vide.

with seed as (
  select *
  from jsonb_to_recordset($hof100$
[
  {"name":"Dino Zoff","display_name":"Dino Zoff","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Dino_Zoff_%281974%29.jpg/500px-Dino_Zoff_%281974%29.jpg","nationality":"Italie","position":"Gardien","goat_positions":["goalkeepers"],"era":"années 1960-1980","clubs":["Udinese","Mantova","Napoli","Juventus"],"national_team":"Italie","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":["1982"],"euro_titles":["1968"],"copa_america_titles":[],"champions_league_titles":[],"fifa_awards":[],"major_records":["Champion du monde à 40 ans","Référence historique des gardiens italiens"],"iconic_moments":["Coupe du Monde 1982","Euro 1968","long règne à la Juventus"],"nickname":"Il Capitano","legacy":"Symbole de calme, longévité et autorité chez les gardiens.","playing_style":"Gardien sobre, placement, lecture, sorties et leadership.","why_legend":"Champion du monde et d'Europe, il reste un modèle de régularité et de maturité au poste.","goat_score":90,"hall_of_fame_tier":"S","contexts":["worldcup","euro"]},
  {"name":"Iker Casillas","display_name":"Iker Casillas","photo_url":"https://images.fotmob.com/image_resources/playerimages/12338.png","nationality":"Espagne","position":"Gardien","goat_positions":["goalkeepers"],"era":"années 2000-2010","clubs":["Real Madrid","Porto"],"national_team":"Espagne","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":["2010"],"euro_titles":["2008","2012"],"copa_america_titles":[],"champions_league_titles":["2000","2002","2014"],"fifa_awards":["IFFHS meilleur gardien"],"major_records":["Capitaine de l'Espagne championne du monde","Légende du Real Madrid"],"iconic_moments":["Arrêt contre Robben en 2010","Décima 2014","Euro 2008 et 2012"],"nickname":"San Iker","legacy":"Un des grands gardiens modernes, associé à la domination Espagne/Real.","playing_style":"Réflexes, explosivité, duel, leadership discret.","why_legend":"Capitaine de la génération espagnole la plus titrée et triple champion d'Europe avec le Real.","goat_score":91,"hall_of_fame_tier":"S","contexts":["worldcup","euro","champions"]},
  {"name":"Manuel Neuer","display_name":"Manuel Neuer","photo_url":"https://images.fotmob.com/image_resources/playerimages/27299.png","nationality":"Allemagne","position":"Gardien","goat_positions":["goalkeepers"],"era":"années 2010-2020","clubs":["Schalke 04","Bayern Munich"],"national_team":"Allemagne","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":["2014"],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":["2013","2020"],"fifa_awards":["The Best FIFA Goalkeeper"],"major_records":["Référence du gardien-libéro moderne","Pilier du Bayern et de l'Allemagne"],"iconic_moments":["Coupe du Monde 2014","Triplé Bayern 2013","Ligue des Champions 2020"],"nickname":"Manu","legacy":"A transformé les exigences modernes du poste par son jeu haut et sa relance.","playing_style":"Gardien-libéro, sorties loin de sa surface, relance, réflexes.","why_legend":"Champion du monde, double champion d'Europe et modèle tactique du gardien moderne.","goat_score":92,"hall_of_fame_tier":"S","contexts":["worldcup","euro","champions"]},
  {"name":"Peter Schmeichel","display_name":"Peter Schmeichel","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Peter_Schmeichel_2012.jpg/500px-Peter_Schmeichel_2012.jpg","nationality":"Danemark","position":"Gardien","goat_positions":["goalkeepers"],"era":"années 1990","clubs":["Brøndby","Manchester United","Sporting CP","Aston Villa","Manchester City"],"national_team":"Danemark","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":[],"euro_titles":["1992"],"copa_america_titles":[],"champions_league_titles":["1999"],"fifa_awards":[],"major_records":["Gardien du triplé 1999 de Manchester United","Champion d'Europe 1992"],"iconic_moments":["Euro 1992","Finale 1999", "années Ferguson"],"nickname":"The Great Dane","legacy":"Gardien dominant, imposant, symbole du Manchester United des années 1990.","playing_style":"Présence physique, réflexes, sorties aériennes, autorité.","why_legend":"Euro 1992, Ligue des Champions 1999 et statut de référence en Premier League.","goat_score":88,"hall_of_fame_tier":"A+","contexts":["euro","champions"]},
  {"name":"Oliver Kahn","display_name":"Oliver Kahn","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Oliver_Kahn_2019.jpg/500px-Oliver_Kahn_2019.jpg","nationality":"Allemagne","position":"Gardien","goat_positions":["goalkeepers"],"era":"années 1990-2000","clubs":["Karlsruher SC","Bayern Munich"],"national_team":"Allemagne","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":[],"euro_titles":["1996"],"copa_america_titles":[],"champions_league_titles":["2001"],"fifa_awards":["Ballon d'Or Coupe du Monde 2002"],"major_records":["Meilleur joueur de la Coupe du Monde 2002","Icône du Bayern"],"iconic_moments":["Ligue des Champions 2001","Coupe du Monde 2002","Euro 1996"],"nickname":"Der Titan","legacy":"Gardien de caractère, intensité mentale et leadership extrême.","playing_style":"Réflexes, agressivité positive, mental, duel et puissance.","why_legend":"Un des rares gardiens à avoir dominé une Coupe du Monde individuellement.","goat_score":88,"hall_of_fame_tier":"A+","contexts":["worldcup","euro","champions"]},
  {"name":"Sepp Maier","display_name":"Sepp Maier","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Sepp_Maier_2012.jpg/500px-Sepp_Maier_2012.jpg","nationality":"Allemagne","position":"Gardien","goat_positions":["goalkeepers"],"era":"années 1960-1970","clubs":["Bayern Munich"],"national_team":"Allemagne","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":["1974"],"euro_titles":["1972"],"copa_america_titles":[],"champions_league_titles":["1974","1975","1976"],"fifa_awards":[],"major_records":["Triple champion d'Europe avec le Bayern","Gardien de l'Allemagne 1974"],"iconic_moments":["Coupe du Monde 1974","Euro 1972","Bayern triple champion d'Europe"],"nickname":"Die Katze von Anzing","legacy":"Pilier d'une des grandes dynasties allemandes et bavaroises.","playing_style":"Réflexes, mobilité, concentration et régularité.","why_legend":"Un palmarès complet club/sélection et une longévité remarquable au Bayern.","goat_score":87,"hall_of_fame_tier":"A+","contexts":["worldcup","euro","champions"]},
  {"name":"Gordon Banks","display_name":"Gordon Banks","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Gordon_Banks_2007.jpg/500px-Gordon_Banks_2007.jpg","nationality":"Angleterre","position":"Gardien","goat_positions":["goalkeepers"],"era":"années 1960-1970","clubs":["Leicester City","Stoke City"],"national_team":"Angleterre","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":["1966"],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":[],"fifa_awards":[],"major_records":["Champion du monde 1966","Auteur de l'arrêt mythique face à Pelé en 1970"],"iconic_moments":["Coupe du Monde 1966","Arrêt contre Pelé en 1970"],"nickname":"Banksy","legacy":"Gardien anglais mythique, associé à un des arrêts les plus célèbres de l'histoire.","playing_style":"Placement, réflexes, sérénité et anticipation.","why_legend":"Champion du monde et auteur d'un geste devenu référence pour tous les gardiens.","goat_score":86,"hall_of_fame_tier":"A+","contexts":["worldcup"]},
  {"name":"Edwin van der Sar","display_name":"Edwin van der Sar","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Edwin_van_der_Sar_2015.jpg/500px-Edwin_van_der_Sar_2015.jpg","nationality":"Pays-Bas","position":"Gardien","goat_positions":["goalkeepers"],"era":"années 1990-2010","clubs":["Ajax","Juventus","Fulham","Manchester United"],"national_team":"Pays-Bas","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":[],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":["1995","2008"],"fifa_awards":[],"major_records":["Champion d'Europe avec Ajax et Manchester United","Référence de relance au poste"],"iconic_moments":["Ajax 1995","Manchester United 2008","finale européenne aux tirs au but"],"nickname":"Edwin","legacy":"Gardien moderne, grand, calme et précieux dans la relance.","playing_style":"Placement, jeu au pied, calme, envergure et expérience.","why_legend":"Deux Ligues des Champions à deux époques différentes et une longévité rare.","goat_score":86,"hall_of_fame_tier":"A+","contexts":["euro","champions"]},
  {"name":"José Luis Chilavert","display_name":"José Luis Chilavert","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Chilavert_2014.jpg/500px-Chilavert_2014.jpg","nationality":"Paraguay","position":"Gardien","goat_positions":["goalkeepers"],"era":"années 1990-2000","clubs":["Vélez Sarsfield","Strasbourg","Peñarol"],"national_team":"Paraguay","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":[],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":[],"fifa_awards":["IFFHS meilleur gardien"],"major_records":["Gardien buteur historique","Légende du Paraguay"],"iconic_moments":["Coupes du Monde 1998 et 2002","Vélez Sarsfield"],"nickname":"Chila","legacy":"Gardien unique par son leadership, ses coups francs et son influence offensive.","playing_style":"Gardien de caractère, jeu au pied, coups francs, autorité.","why_legend":"Un gardien-buteur emblématique qui a changé l'image du poste en Amérique du Sud.","goat_score":82,"hall_of_fame_tier":"A","contexts":["worldcup"]},
  {"name":"Dida","display_name":"Dida","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Dida_2012.jpg/500px-Dida_2012.jpg","nationality":"Brésil","position":"Gardien","goat_positions":["goalkeepers"],"era":"années 1990-2000","clubs":["Cruzeiro","Corinthians","AC Milan"],"national_team":"Brésil","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":["2002"],"euro_titles":[],"copa_america_titles":["1999"],"champions_league_titles":["2003","2007"],"fifa_awards":[],"major_records":["Double champion d'Europe avec l'AC Milan","Gardien majeur du Brésil moderne"],"iconic_moments":["Ligue des Champions 2003","Ligue des Champions 2007","Brésil 2002"],"nickname":"Dida","legacy":"Gardien brésilien de référence, sobre, puissant et décisif à Milan.","playing_style":"Réflexes, puissance, détente et calme dans les grands matchs.","why_legend":"Mondial, Copa América et deux Ligues des Champions : un palmarès rare pour un gardien.","goat_score":84,"hall_of_fame_tier":"A","contexts":["worldcup","champions"]},
  {"name":"René Higuita","display_name":"René Higuita","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Rene_Higuita_2012.jpg/500px-Rene_Higuita_2012.jpg","nationality":"Colombie","position":"Gardien","goat_positions":["goalkeepers"],"era":"années 1980-1990","clubs":["Atlético Nacional","Real Valladolid"],"national_team":"Colombie","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":[],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":[],"fifa_awards":[],"major_records":["Icône du gardien-libéro spectaculaire","Auteur du coup du scorpion"],"iconic_moments":["Coup du scorpion","Atlético Nacional","Coupe du Monde 1990"],"nickname":"El Loco","legacy":"Gardien spectaculaire qui a repoussé les limites du rôle par sa prise de risque.","playing_style":"Gardien-libéro, jeu au pied, sorties audacieuses, gestes techniques.","why_legend":"Plus qu'un palmarès : une influence culturelle et stylistique immense sur le poste.","goat_score":80,"hall_of_fame_tier":"A","contexts":["worldcup"]},
  {"name":"Emiliano Martínez","display_name":"Emiliano Martínez","photo_url":"https://images.fotmob.com/image_resources/playerimages/268375.png","nationality":"Argentine","position":"Gardien","goat_positions":["goalkeepers"],"era":"années 2020","clubs":["Arsenal","Aston Villa"],"national_team":"Argentine","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":["2022"],"euro_titles":[],"copa_america_titles":["2021","2024"],"champions_league_titles":[],"fifa_awards":["The Best FIFA Goalkeeper","Trophée Yachine"],"major_records":["Gardien décisif de l'Argentine championne du monde 2022"],"iconic_moments":["Arrêt face à Kolo Muani en 2022","Tirs au but Coupe du Monde 2022","Copa América 2021"],"nickname":"Dibu","legacy":"Gardien émotionnel et décisif, symbole de l'Argentine récente.","playing_style":"Duel, penalties, mental, provocations psychologiques et réflexes.","why_legend":"Son rôle dans la finale 2022 et les séances de tirs au but argentines l'a fait entrer dans l'histoire.","goat_score":81,"hall_of_fame_tier":"A","contexts":["worldcup"]},

  {"name":"Franco Baresi","display_name":"Franco Baresi","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Franco_Baresi.jpg/500px-Franco_Baresi.jpg","nationality":"Italie","position":"Défenseur","goat_positions":["defenders"],"era":"années 1980-1990","clubs":["AC Milan"],"national_team":"Italie","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":["1982"],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":["1989","1990","1994"],"fifa_awards":[],"major_records":["Libéro mythique de l'AC Milan","Pilier de la défense Sacchi/Capello"],"iconic_moments":["AC Milan européen","Finale Coupe du Monde 1994","dynastie Milan"],"nickname":"Piscinin","legacy":"Un des plus grands défenseurs de l'histoire par son anticipation et son leadership.","playing_style":"Libéro, placement, relance, commandement de ligne et lecture.","why_legend":"Capitaine d'une des meilleures défenses de l'histoire du football de club.","goat_score":92,"hall_of_fame_tier":"S","contexts":["worldcup","euro","champions"]},
  {"name":"Roberto Carlos","display_name":"Roberto Carlos","photo_url":"https://images.fotmob.com/image_resources/playerimages/12330.png","nationality":"Brésil","position":"Défenseur","goat_positions":["defenders"],"era":"années 1990-2000","clubs":["Palmeiras","Inter","Real Madrid","Fenerbahçe"],"national_team":"Brésil","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":["2002"],"euro_titles":[],"copa_america_titles":["1997","1999"],"champions_league_titles":["1998","2000","2002"],"fifa_awards":[],"major_records":["Latéral gauche iconique du Real Madrid","Frappe mythique contre la France"],"iconic_moments":["Coup franc face à la France 1997","Coupe du Monde 2002","Galactiques"],"nickname":"RC3","legacy":"Latéral offensif emblématique, puissance, vitesse et frappe hors norme.","playing_style":"Latéral explosif, centres, frappes, volume et puissance.","why_legend":"Il a redéfini l'image du latéral gauche offensif au niveau mondial.","goat_score":88,"hall_of_fame_tier":"A+","contexts":["worldcup","champions"]},
  {"name":"Cafu","display_name":"Cafu","photo_url":"https://images.fotmob.com/image_resources/playerimages/1193.png","nationality":"Brésil","position":"Défenseur","goat_positions":["defenders"],"era":"années 1990-2000","clubs":["São Paulo","Roma","AC Milan"],"national_team":"Brésil","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":["1994","2002"],"euro_titles":[],"copa_america_titles":["1997","1999"],"champions_league_titles":["2007"],"fifa_awards":[],"major_records":["Seul joueur à avoir disputé trois finales de Coupe du Monde consécutives","Capitaine du Brésil 2002"],"iconic_moments":["Soulève la Coupe du Monde 2002","Roma championne 2001","AC Milan 2007"],"nickname":"Il Pendolino","legacy":"Latéral droit de référence par son endurance, sa régularité et son leadership.","playing_style":"Latéral de couloir, vitesse, répétition des courses, centres et solidité.","why_legend":"Deux Coupes du Monde et une constance exceptionnelle au poste de latéral droit.","goat_score":89,"hall_of_fame_tier":"S","contexts":["worldcup","champions"]},
  {"name":"Fabio Cannavaro","display_name":"Fabio Cannavaro","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Fabio_Cannavaro_2015.jpg/500px-Fabio_Cannavaro_2015.jpg","nationality":"Italie","position":"Défenseur","goat_positions":["defenders"],"era":"années 1990-2000","clubs":["Napoli","Parma","Inter","Juventus","Real Madrid"],"national_team":"Italie","ballon_dor_count":1,"ballon_dor_years":["2006"],"world_cup_titles":["2006"],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":[],"fifa_awards":["FIFA World Player 2006"],"major_records":["Ballon d'Or défenseur en 2006","Capitaine de l'Italie championne du monde"],"iconic_moments":["Coupe du Monde 2006","Ballon d'Or 2006","défense italienne"],"nickname":"Canna","legacy":"Défenseur central compact, dominateur dans le duel et symbole du Mondial 2006.","playing_style":"Anticipation, agressivité, duel aérien, leadership et lecture.","why_legend":"Un des rares défenseurs Ballon d'Or, porté par une Coupe du Monde magistrale.","goat_score":88,"hall_of_fame_tier":"A+","contexts":["worldcup","euro","champions"]},
  {"name":"Marcel Desailly","display_name":"Marcel Desailly","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Marcel_Desailly_2011.jpg/500px-Marcel_Desailly_2011.jpg","nationality":"France","position":"Défenseur / milieu défensif","goat_positions":["defenders"],"era":"années 1990-2000","clubs":["Nantes","Marseille","AC Milan","Chelsea"],"national_team":"France","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":["1998"],"euro_titles":["2000"],"copa_america_titles":[],"champions_league_titles":["1993","1994"],"fifa_awards":[],"major_records":["Vainqueur de deux Ligues des Champions avec deux clubs différents","Cadre France 1998-2000"],"iconic_moments":["OM 1993","AC Milan 1994","France 1998"],"nickname":"The Rock","legacy":"Défenseur puissant et intelligent, pilier des grandes équipes françaises et milanaises.","playing_style":"Puissance, duel, couverture, relance simple et discipline tactique.","why_legend":"Mondial, Euro et deux Coupes d'Europe : un palmarès d'élite pour un défenseur.","goat_score":85,"hall_of_fame_tier":"A+","contexts":["worldcup","euro","champions"]},
  {"name":"Bobby Moore","display_name":"Bobby Moore","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Bobby_Moore_1969.jpg/500px-Bobby_Moore_1969.jpg","nationality":"Angleterre","position":"Défenseur","goat_positions":["defenders"],"era":"années 1960-1970","clubs":["West Ham United","Fulham"],"national_team":"Angleterre","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":["1966"],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":[],"fifa_awards":[],"major_records":["Capitaine de l'Angleterre championne du monde","Référence morale du football anglais"],"iconic_moments":["Coupe du Monde 1966","duel contre Pelé en 1970"],"nickname":"Bobby","legacy":"Défenseur élégant et capitaine mythique de l'unique titre mondial anglais.","playing_style":"Placement, tacle propre, relance, calme et autorité.","why_legend":"Il a soulevé la Coupe du Monde pour l'Angleterre et reste une référence de défense propre.","goat_score":87,"hall_of_fame_tier":"A+","contexts":["worldcup"]},
  {"name":"Carlos Alberto","display_name":"Carlos Alberto","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Carlos_Alberto_Torres_1970.jpg/500px-Carlos_Alberto_Torres_1970.jpg","nationality":"Brésil","position":"Défenseur","goat_positions":["defenders"],"era":"années 1960-1970","clubs":["Fluminense","Santos","New York Cosmos"],"national_team":"Brésil","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":["1970"],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":[],"fifa_awards":[],"major_records":["Capitaine du Brésil 1970","Auteur du but iconique en finale 1970"],"iconic_moments":["Finale Coupe du Monde 1970","Brésil de Pelé"],"nickname":"Capita","legacy":"Latéral et capitaine mythique de l'une des plus grandes équipes de l'histoire.","playing_style":"Latéral droit élégant, projection, frappe, leadership.","why_legend":"Son but en finale 1970 symbolise le football brésilien total.","goat_score":86,"hall_of_fame_tier":"A+","contexts":["worldcup"]},
  {"name":"Daniel Passarella","display_name":"Daniel Passarella","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Daniel_Passarella_1978.jpg/500px-Daniel_Passarella_1978.jpg","nationality":"Argentine","position":"Défenseur","goat_positions":["defenders"],"era":"années 1970-1980","clubs":["River Plate","Fiorentina","Inter"],"national_team":"Argentine","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":["1978","1986"],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":[],"fifa_awards":[],"major_records":["Capitaine de l'Argentine 1978","Défenseur buteur majeur"],"iconic_moments":["Coupe du Monde 1978","River Plate","Serie A"],"nickname":"El Gran Capitán","legacy":"Défenseur central leader et buteur, référence argentine du poste.","playing_style":"Jeu aérien, agressivité, buts, leadership et sens de l'anticipation.","why_legend":"Deux titres mondiaux et un profil rare de défenseur décisif offensivement.","goat_score":85,"hall_of_fame_tier":"A+","contexts":["worldcup"]},
  {"name":"Carles Puyol","display_name":"Carles Puyol","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Carles_Puyol_2011.jpg/500px-Carles_Puyol_2011.jpg","nationality":"Espagne","position":"Défenseur","goat_positions":["defenders"],"era":"années 2000-2010","clubs":["FC Barcelone"],"national_team":"Espagne","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":["2010"],"euro_titles":["2008"],"copa_america_titles":[],"champions_league_titles":["2006","2009","2011"],"fifa_awards":[],"major_records":["Capitaine emblématique du Barça","But décisif contre l'Allemagne en 2010"],"iconic_moments":["Demi-finale Mondial 2010","Barça Guardiola","triplé 2009"],"nickname":"Tarzan","legacy":"Leader défensif, courage et âme compétitive du Barça et de l'Espagne.","playing_style":"Duel, engagement, couverture, leadership et polyvalence défensive.","why_legend":"Leader d'une des générations club/sélection les plus dominantes de l'histoire.","goat_score":86,"hall_of_fame_tier":"A+","contexts":["worldcup","euro","champions"]},
  {"name":"Philipp Lahm","display_name":"Philipp Lahm","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Philipp_Lahm_2017.jpg/500px-Philipp_Lahm_2017.jpg","nationality":"Allemagne","position":"Défenseur / milieu","goat_positions":["defenders","midfielders"],"era":"années 2000-2010","clubs":["Bayern Munich","VfB Stuttgart"],"national_team":"Allemagne","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":["2014"],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":["2013"],"fifa_awards":[],"major_records":["Capitaine de l'Allemagne 2014","Latéral moderne de référence"],"iconic_moments":["Coupe du Monde 2014","Triplé Bayern 2013","reconversion au milieu"],"nickname":"Magic Dwarf","legacy":"Intelligence tactique, propreté technique et leadership calme.","playing_style":"Latéral intelligent, placement, relance, polyvalence, précision.","why_legend":"Capitaine champion du monde et symbole de l'excellence tactique allemande.","goat_score":86,"hall_of_fame_tier":"A+","contexts":["worldcup","euro","champions"]},
  {"name":"Gerard Piqué","display_name":"Gerard Piqué","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Gerard_Piqu%C3%A9_2018.jpg/500px-Gerard_Piqu%C3%A9_2018.jpg","nationality":"Espagne","position":"Défenseur","goat_positions":["defenders"],"era":"années 2000-2020","clubs":["Manchester United","FC Barcelone"],"national_team":"Espagne","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":["2010"],"euro_titles":["2012"],"copa_america_titles":[],"champions_league_titles":["2008","2009","2011","2015"],"fifa_awards":[],"major_records":["Pilier du Barça et de l'Espagne","Défenseur relanceur majeur"],"iconic_moments":["Coupe du Monde 2010","Barça Guardiola","Ligue des Champions 2015"],"nickname":"Geri","legacy":"Défenseur moderne, relanceur, symbole du Barça de possession.","playing_style":"Défenseur central technique, relance, anticipation, jeu aérien.","why_legend":"Palmarès immense en club et sélection, rôle clé dans deux cycles historiques.","goat_score":84,"hall_of_fame_tier":"A","contexts":["worldcup","euro","champions"]},
  {"name":"Alessandro Nesta","display_name":"Alessandro Nesta","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Alessandro_Nesta_2018.jpg/500px-Alessandro_Nesta_2018.jpg","nationality":"Italie","position":"Défenseur","goat_positions":["defenders"],"era":"années 1990-2000","clubs":["Lazio","AC Milan"],"national_team":"Italie","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":["2006"],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":["2003","2007"],"fifa_awards":[],"major_records":["Défenseur italien d'élite","Double champion d'Europe avec Milan"],"iconic_moments":["AC Milan 2003 et 2007","Italie 2006","Lazio champion"],"nickname":"Nesta","legacy":"Défenseur élégant, tacle propre et sens du placement exceptionnel.","playing_style":"Anticipation, tacle, élégance, couverture et duel.","why_legend":"Un des défenseurs les plus raffinés de son époque, avec un palmarès majeur.","goat_score":86,"hall_of_fame_tier":"A+","contexts":["worldcup","euro","champions"]},
  {"name":"Gaetano Scirea","display_name":"Gaetano Scirea","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Gaetano_Scirea.jpg/500px-Gaetano_Scirea.jpg","nationality":"Italie","position":"Défenseur","goat_positions":["defenders"],"era":"années 1970-1980","clubs":["Atalanta","Juventus"],"national_team":"Italie","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":["1982"],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":["1985"],"fifa_awards":[],"major_records":["Libéro élégant de la Juventus et de l'Italie","Palmarès complet en club"],"iconic_moments":["Coupe du Monde 1982","Juventus années 1980"],"nickname":"Scirea","legacy":"Modèle de défense propre, élégante et intelligente.","playing_style":"Libéro calme, relance, lecture, couverture et fair-play.","why_legend":"Champion du monde et référence morale/technique du poste de libéro.","goat_score":86,"hall_of_fame_tier":"A+","contexts":["worldcup","champions"]},
  {"name":"Nilton Santos","display_name":"Nilton Santos","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Nilton_Santos_1962.jpg/500px-Nilton_Santos_1962.jpg","nationality":"Brésil","position":"Défenseur","goat_positions":["defenders"],"era":"années 1950-1960","clubs":["Botafogo"],"national_team":"Brésil","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":["1958","1962"],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":[],"fifa_awards":[],"major_records":["Pionnier du latéral offensif","Double champion du monde"],"iconic_moments":["Coupe du Monde 1958","Coupe du Monde 1962","Botafogo"],"nickname":"A Enciclopédia","legacy":"Un des premiers latéraux à attaquer avec intelligence et créativité.","playing_style":"Latéral gauche technique, projection, défense et lecture.","why_legend":"Il a ouvert la voie au latéral moderne dans le Brésil champion du monde.","goat_score":87,"hall_of_fame_tier":"A+","contexts":["worldcup"]},
  {"name":"Dani Alves","display_name":"Dani Alves","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Dani_Alves_2019.jpg/500px-Dani_Alves_2019.jpg","nationality":"Brésil","position":"Défenseur","goat_positions":["defenders"],"era":"années 2000-2020","clubs":["Bahia","Sevilla","FC Barcelone","Juventus","PSG","São Paulo"],"national_team":"Brésil","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":[],"euro_titles":[],"copa_america_titles":["2007","2019"],"champions_league_titles":["2009","2011","2015"],"fifa_awards":[],"major_records":["Un des joueurs les plus titrés de l'histoire","Latéral majeur du Barça"],"iconic_moments":["Barça Guardiola","Copa América 2019","triplé 2015"],"nickname":"Dani","legacy":"Latéral offensif ultra créatif, parfois presque meneur depuis son couloir.","playing_style":"Projection, centres, combinaisons, technique et agressivité offensive.","why_legend":"Palmarès immense, rôle clé dans le Barça historique et influence sur les latéraux modernes.","goat_score":87,"hall_of_fame_tier":"A+","contexts":["worldcup","champions"]},
  {"name":"Javier Zanetti","display_name":"Javier Zanetti","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Javier_Zanetti_2011.jpg/500px-Javier_Zanetti_2011.jpg","nationality":"Argentine","position":"Défenseur / milieu","goat_positions":["defenders","midfielders"],"era":"années 1990-2010","clubs":["Banfield","Inter"],"national_team":"Argentine","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":[],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":["2010"],"fifa_awards":[],"major_records":["Capitaine historique de l'Inter","Symbole de longévité et loyauté"],"iconic_moments":["Triplé Inter 2010","années Inter","sélection argentine"],"nickname":"Pupi","legacy":"Modèle de professionnalisme, polyvalence et régularité.","playing_style":"Latéral/milieu, endurance, conduite, duel, relance et discipline.","why_legend":"Capitaine du triplé de l'Inter et figure majeure du football argentin en Europe.","goat_score":85,"hall_of_fame_tier":"A+","contexts":["worldcup","champions"]},
  {"name":"Lilian Thuram","display_name":"Lilian Thuram","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Lilian_Thuram_2008.jpg/500px-Lilian_Thuram_2008.jpg","nationality":"France","position":"Défenseur","goat_positions":["defenders"],"era":"années 1990-2000","clubs":["Monaco","Parma","Juventus","FC Barcelone"],"national_team":"France","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":["1998"],"euro_titles":["2000"],"copa_america_titles":[],"champions_league_titles":[],"fifa_awards":[],"major_records":["Héros de la demi-finale 1998","Recordman de sélections françaises pendant longtemps"],"iconic_moments":["Doublé contre la Croatie en 1998","Euro 2000","Juventus"],"nickname":"Tutu","legacy":"Défenseur français majeur, symbole de solidité et d'intelligence.","playing_style":"Latéral/défenseur central, lecture, duel, puissance et sobriété.","why_legend":"Ses deux buts en demi-finale 1998 font partie des moments fondateurs du football français.","goat_score":85,"hall_of_fame_tier":"A+","contexts":["worldcup","euro","champions"]},
  {"name":"Ashley Cole","display_name":"Ashley Cole","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Ashley_Cole_2012.jpg/500px-Ashley_Cole_2012.jpg","nationality":"Angleterre","position":"Défenseur","goat_positions":["defenders"],"era":"années 2000-2010","clubs":["Arsenal","Chelsea","Roma","LA Galaxy"],"national_team":"Angleterre","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":[],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":["2012"],"fifa_awards":[],"major_records":["Référence du latéral gauche en Premier League","Invincible avec Arsenal"],"iconic_moments":["Arsenal Invincibles","Chelsea champion d'Europe 2012"],"nickname":"Ash","legacy":"Latéral gauche défensif/offensif de très haut niveau, modèle de duel face aux ailiers.","playing_style":"Vitesse, duel, couverture, projection et discipline.","why_legend":"Un des meilleurs latéraux de Premier League, champion d'Europe avec Chelsea.","goat_score":82,"hall_of_fame_tier":"A","contexts":["worldcup","euro","champions"]},

  {"name":"Andrea Pirlo","display_name":"Andrea Pirlo","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Andrea_Pirlo_2017.jpg/500px-Andrea_Pirlo_2017.jpg","nationality":"Italie","position":"Milieu","goat_positions":["midfielders"],"era":"années 2000-2010","clubs":["Inter","AC Milan","Juventus","New York City FC"],"national_team":"Italie","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":["2006"],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":["2003","2007"],"fifa_awards":[],"major_records":["Regista moderne de référence","Maître des coups francs et du tempo"],"iconic_moments":["Coupe du Monde 2006","AC Milan 2003 et 2007","Juventus Conte"],"nickname":"Il Maestro","legacy":"A redéfini le rôle de meneur reculé par son calme et sa qualité de passe.","playing_style":"Regista, passes longues, coups francs, tempo et intelligence.","why_legend":"Champion du monde, double champion d'Europe et référence absolue du milieu reculé.","goat_score":89,"hall_of_fame_tier":"S","contexts":["worldcup","euro","champions"]},
  {"name":"Lothar Matthäus","display_name":"Lothar Matthäus","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Lothar_Matthaeus_2019.jpg/500px-Lothar_Matthaeus_2019.jpg","nationality":"Allemagne","position":"Milieu","goat_positions":["midfielders"],"era":"années 1980-1990","clubs":["Borussia Mönchengladbach","Bayern Munich","Inter"],"national_team":"Allemagne","ballon_dor_count":1,"ballon_dor_years":["1990"],"world_cup_titles":["1990"],"euro_titles":["1980"],"copa_america_titles":[],"champions_league_titles":[],"fifa_awards":["FIFA World Player 1991"],"major_records":["Capitaine de l'Allemagne 1990","Milieu total"],"iconic_moments":["Coupe du Monde 1990","Inter Milan","Bayern Munich"],"nickname":"Lothar","legacy":"Milieu complet, puissance, leadership et influence sur plusieurs décennies.","playing_style":"Box-to-box, frappe, duel, projection, organisation et leadership.","why_legend":"Ballon d'Or, champion du monde et modèle du milieu complet moderne.","goat_score":92,"hall_of_fame_tier":"S","contexts":["worldcup","euro","champions"]},
  {"name":"Ruud Gullit","display_name":"Ruud Gullit","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Ruud_Gullit_2012.jpg/500px-Ruud_Gullit_2012.jpg","nationality":"Pays-Bas","position":"Milieu / attaquant","goat_positions":["midfielders","attackers"],"era":"années 1980-1990","clubs":["Feyenoord","PSV","AC Milan","Chelsea"],"national_team":"Pays-Bas","ballon_dor_count":1,"ballon_dor_years":["1987"],"world_cup_titles":[],"euro_titles":["1988"],"copa_america_titles":[],"champions_league_titles":["1989","1990"],"fifa_awards":[],"major_records":["Capitaine des Pays-Bas champions d'Europe 1988","Pilier du grand Milan"],"iconic_moments":["Euro 1988","AC Milan Sacchi","Ballon d'Or 1987"],"nickname":"Tulipe noire","legacy":"Joueur total, physique, technique et tactiquement très moderne.","playing_style":"Puissance, polyvalence, jeu aérien, technique et projection.","why_legend":"Ballon d'Or, Euro et Milan européen : un profil complet et spectaculaire.","goat_score":90,"hall_of_fame_tier":"S","contexts":["euro","champions"]},
  {"name":"Zico","display_name":"Zico","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Zico_2012.jpg/500px-Zico_2012.jpg","nationality":"Brésil","position":"Milieu offensif","goat_positions":["midfielders"],"era":"années 1970-1980","clubs":["Flamengo","Udinese","Kashima Antlers"],"national_team":"Brésil","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":[],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":[],"fifa_awards":[],"major_records":["Légende de Flamengo","Un des plus grands meneurs brésiliens"],"iconic_moments":["Flamengo champion du monde des clubs 1981","Brésil 1982","Udinese"],"nickname":"Galinho","legacy":"Meneur créatif, buteur, maître des coups francs et symbole du Brésil romantique.","playing_style":"Meneur-buteur, coups francs, vision, finition et créativité.","why_legend":"Malgré l'absence de Mondial, son talent et son influence restent immenses.","goat_score":90,"hall_of_fame_tier":"S","contexts":["worldcup"]},
  {"name":"Sócrates","display_name":"Sócrates","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Socrates_1983.jpg/500px-Socrates_1983.jpg","nationality":"Brésil","position":"Milieu","goat_positions":["midfielders"],"era":"années 1970-1980","clubs":["Botafogo-SP","Corinthians","Fiorentina","Flamengo","Santos"],"national_team":"Brésil","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":[],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":[],"fifa_awards":[],"major_records":["Capitaine du Brésil 1982","Icône culturelle et politique"],"iconic_moments":["Brésil 1982","Democracia Corinthiana"],"nickname":"Doutor","legacy":"Milieu élégant, intellectuel, symbole du football brésilien artistique et engagé.","playing_style":"Talonnades, vision, passes, taille imposante et élégance.","why_legend":"Son aura dépasse le terrain : technique, leadership et impact culturel.","goat_score":86,"hall_of_fame_tier":"A+","contexts":["worldcup"]},
  {"name":"Frank Rijkaard","display_name":"Frank Rijkaard","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Frank_Rijkaard_1988.jpg/500px-Frank_Rijkaard_1988.jpg","nationality":"Pays-Bas","position":"Milieu défensif","goat_positions":["midfielders","defenders"],"era":"années 1980-1990","clubs":["Ajax","AC Milan"],"national_team":"Pays-Bas","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":[],"euro_titles":["1988"],"copa_america_titles":[],"champions_league_titles":["1989","1990","1995"],"fifa_awards":[],"major_records":["Pilier du Milan Sacchi","Champion d'Europe avec les Pays-Bas"],"iconic_moments":["Euro 1988","AC Milan 1989-1990","Ajax 1995"],"nickname":"Frank","legacy":"Milieu défensif complet, capable d'équilibrer et de jouer avec élégance.","playing_style":"Récupération, relance, duel, puissance et intelligence tactique.","why_legend":"Euro et trois Coupes d'Europe dans deux clubs majeurs, profil complet et moderne.","goat_score":87,"hall_of_fame_tier":"A+","contexts":["euro","champions"]},
  {"name":"Clarence Seedorf","display_name":"Clarence Seedorf","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Clarence_Seedorf_2011.jpg/500px-Clarence_Seedorf_2011.jpg","nationality":"Pays-Bas","position":"Milieu","goat_positions":["midfielders"],"era":"années 1990-2010","clubs":["Ajax","Real Madrid","Inter","AC Milan","Botafogo"],"national_team":"Pays-Bas","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":[],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":["1995","1998","2003","2007"],"fifa_awards":[],"major_records":["Seul joueur à gagner la Ligue des Champions avec trois clubs différents","Milieu européen majeur"],"iconic_moments":["Ajax 1995","Real Madrid 1998","Milan 2003 et 2007"],"nickname":"Clarence","legacy":"Milieu puissant, technique, professionnel et symbole de réussite européenne.","playing_style":"Milieu polyvalent, frappe, conservation, puissance et expérience.","why_legend":"Quatre Ligues des Champions avec trois clubs : un cas unique.","goat_score":86,"hall_of_fame_tier":"A+","contexts":["worldcup","euro","champions"]},
  {"name":"Michael Laudrup","display_name":"Michael Laudrup","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Michael_Laudrup_2016.jpg/500px-Michael_Laudrup_2016.jpg","nationality":"Danemark","position":"Milieu offensif","goat_positions":["midfielders"],"era":"années 1980-1990","clubs":["Juventus","FC Barcelone","Real Madrid","Ajax"],"national_team":"Danemark","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":[],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":["1992"],"fifa_awards":[],"major_records":["Meneur de la Dream Team du Barça","Un des plus grands passeurs de l'histoire"],"iconic_moments":["Barça Cruyff","Real Madrid","Ligue des Champions 1992"],"nickname":"Laudrup","legacy":"Créateur élégant, visionnaire et influence majeure du football de possession.","playing_style":"Passe, vision, conduite, feintes et calme créatif.","why_legend":"Un des joueurs les plus admirés par ses pairs pour sa qualité de passe et son intelligence.","goat_score":87,"hall_of_fame_tier":"A+","contexts":["worldcup","euro","champions"]},
  {"name":"Dennis Bergkamp","display_name":"Dennis Bergkamp","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Dennis_Bergkamp_2014.jpg/500px-Dennis_Bergkamp_2014.jpg","nationality":"Pays-Bas","position":"Attaquant / meneur","goat_positions":["attackers","midfielders"],"era":"années 1990-2000","clubs":["Ajax","Inter","Arsenal"],"national_team":"Pays-Bas","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":[],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":[],"fifa_awards":[],"major_records":["Icône d'Arsenal","Auteur de buts parmi les plus techniques de l'histoire"],"iconic_moments":["But contre l'Argentine 1998","Arsenal Invincibles","années Wenger"],"nickname":"The Iceman","legacy":"Attaquant créatif d'une finesse rare, symbole de maîtrise technique.","playing_style":"Contrôle orienté, passe, finition, vision et sang-froid.","why_legend":"Son niveau technique et ses buts iconiques l'ont rendu intemporel.","goat_score":86,"hall_of_fame_tier":"A+","contexts":["worldcup","euro","champions"]},
  {"name":"Patrick Vieira","display_name":"Patrick Vieira","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Patrick_Vieira_2018.jpg/500px-Patrick_Vieira_2018.jpg","nationality":"France","position":"Milieu","goat_positions":["midfielders"],"era":"années 1990-2000","clubs":["Cannes","AC Milan","Arsenal","Juventus","Inter","Manchester City"],"national_team":"France","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":["1998"],"euro_titles":["2000"],"copa_america_titles":[],"champions_league_titles":[],"fifa_awards":[],"major_records":["Capitaine des Invincibles d'Arsenal","Milieu box-to-box de référence"],"iconic_moments":["Arsenal Invincibles","France 1998-2000","duels avec Roy Keane"],"nickname":"Pat","legacy":"Milieu dominant physiquement et tactiquement, leader d'Arsenal.","playing_style":"Box-to-box, puissance, récupération, projection, leadership.","why_legend":"Champion du monde, champion d'Europe et capitaine d'une équipe invaincue en Premier League.","goat_score":85,"hall_of_fame_tier":"A+","contexts":["worldcup","euro","champions"]},
  {"name":"Steven Gerrard","display_name":"Steven Gerrard","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Steven_Gerrard_2014.jpg/500px-Steven_Gerrard_2014.jpg","nationality":"Angleterre","position":"Milieu","goat_positions":["midfielders"],"era":"années 2000-2010","clubs":["Liverpool","LA Galaxy"],"national_team":"Angleterre","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":[],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":["2005"],"fifa_awards":[],"major_records":["Capitaine iconique de Liverpool","Héros d'Istanbul 2005"],"iconic_moments":["Finale Ligue des Champions 2005","finale FA Cup 2006","années Liverpool"],"nickname":"Stevie G","legacy":"Milieu leader, explosif, symbole de loyauté et de moments décisifs.","playing_style":"Frappe, projection, passes longues, tacle, leadership.","why_legend":"Il a incarné Liverpool et signé une des plus grandes finales européennes de l'histoire.","goat_score":85,"hall_of_fame_tier":"A+","contexts":["worldcup","euro","champions"]},
  {"name":"Paul Scholes","display_name":"Paul Scholes","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Paul_Scholes_2017.jpg/500px-Paul_Scholes_2017.jpg","nationality":"Angleterre","position":"Milieu","goat_positions":["midfielders"],"era":"années 1990-2010","clubs":["Manchester United"],"national_team":"Angleterre","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":[],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":["1999","2008"],"fifa_awards":[],"major_records":["Milieu historique de Manchester United","Référence de passe et frappe"],"iconic_moments":["Triplé 1999","Ligue des Champions 2008","années Ferguson"],"nickname":"Scholesy","legacy":"Milieu admiré pour sa qualité de passe, sa vision et sa frappe.","playing_style":"Passe longue, frappe, tempo, déplacements et intelligence.","why_legend":"Pilier discret mais essentiel d'une dynastie de Manchester United.","goat_score":84,"hall_of_fame_tier":"A","contexts":["worldcup","euro","champions"]},
  {"name":"Frank Lampard","display_name":"Frank Lampard","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Frank_Lampard_2017.jpg/500px-Frank_Lampard_2017.jpg","nationality":"Angleterre","position":"Milieu","goat_positions":["midfielders"],"era":"années 2000-2010","clubs":["West Ham United","Chelsea","Manchester City","New York City FC"],"national_team":"Angleterre","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":[],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":["2012"],"fifa_awards":[],"major_records":["Meilleur buteur historique de Chelsea","Milieu buteur de référence"],"iconic_moments":["Ligue des Champions 2012","Chelsea Mourinho","buts depuis le milieu"],"nickname":"Lamps","legacy":"Un des milieux les plus prolifiques de l'histoire moderne.","playing_style":"Projection, frappe, arrivée dans la surface, passes et régularité.","why_legend":"Milieu buteur exceptionnel et figure centrale du Chelsea moderne.","goat_score":84,"hall_of_fame_tier":"A","contexts":["worldcup","euro","champions"]},
  {"name":"Toni Kroos","display_name":"Toni Kroos","photo_url":"https://images.fotmob.com/image_resources/playerimages/95078.png","nationality":"Allemagne","position":"Milieu","goat_positions":["midfielders"],"era":"années 2010-2020","clubs":["Bayern Munich","Bayer Leverkusen","Real Madrid"],"national_team":"Allemagne","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":["2014"],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":["2013","2016","2017","2018","2022","2024"],"fifa_awards":[],"major_records":["6 Ligues des Champions","Métronome du Real Madrid"],"iconic_moments":["Coupe du Monde 2014","Real Madrid européen","passe et contrôle du tempo"],"nickname":"Toni","legacy":"Milieu de contrôle absolu, précision de passe et influence stratégique.","playing_style":"Passe courte/longue, orientation, tempo, calme et frappe lointaine.","why_legend":"Son palmarès européen et sa précision en font un des grands milieux de l'ère moderne.","goat_score":88,"hall_of_fame_tier":"A+","contexts":["worldcup","euro","champions"]},
  {"name":"Kevin De Bruyne","display_name":"Kevin De Bruyne","photo_url":"https://images.fotmob.com/image_resources/playerimages/156592.png","nationality":"Belgique","position":"Milieu","goat_positions":["midfielders"],"era":"années 2010-2020","clubs":["Genk","Chelsea","Wolfsburg","Manchester City"],"national_team":"Belgique","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":[],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":["2023"],"fifa_awards":[],"major_records":["Meneur de Manchester City Guardiola","Un des meilleurs passeurs modernes"],"iconic_moments":["Triplé 2023 avec City","Belgique 2018","Premier League dominante"],"nickname":"KDB","legacy":"Créateur moderne de référence par la qualité et la variété de ses passes.","playing_style":"Passes cassantes, centres, frappe, vision, transitions.","why_legend":"Il a incarné la créativité du Manchester City de Guardiola au plus haut niveau.","goat_score":86,"hall_of_fame_tier":"A+","contexts":["worldcup","euro","champions"]},
  {"name":"Roberto Rivelino","display_name":"Roberto Rivelino","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Rivelino_1974.jpg/500px-Rivelino_1974.jpg","nationality":"Brésil","position":"Milieu offensif","goat_positions":["midfielders"],"era":"années 1960-1970","clubs":["Corinthians","Fluminense","Al Hilal"],"national_team":"Brésil","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":["1970"],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":[],"fifa_awards":[],"major_records":["Gaucher magique du Brésil 1970","Maître de l'elástico"],"iconic_moments":["Coupe du Monde 1970","Brésil de Pelé","Fluminense"],"nickname":"Riva","legacy":"Créateur brésilien puissant et technique, influence majeure sur les dribbleurs.","playing_style":"Gaucher, frappe, dribble, elástico, passes verticales.","why_legend":"Pièce majeure du Brésil 1970 et symbole du flair brésilien.","goat_score":86,"hall_of_fame_tier":"A+","contexts":["worldcup"]},
  {"name":"Didi","display_name":"Didi","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Didi_1958.jpg/500px-Didi_1958.jpg","nationality":"Brésil","position":"Milieu","goat_positions":["midfielders"],"era":"années 1950-1960","clubs":["Fluminense","Botafogo","Real Madrid"],"national_team":"Brésil","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":["1958","1962"],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":[],"fifa_awards":["Meilleur joueur Coupe du Monde 1958"],"major_records":["Architecte du Brésil 1958 et 1962","Inventeur du coup franc feuille morte"],"iconic_moments":["Coupe du Monde 1958","Coupe du Monde 1962"],"nickname":"Didi","legacy":"Milieu élégant et cerveau des premières grandes équipes brésiliennes championnes du monde.","playing_style":"Passe, tempo, coups francs, vision et calme.","why_legend":"Double champion du monde, il fut le chef d'orchestre du Brésil avant l'ère moderne.","goat_score":88,"hall_of_fame_tier":"A+","contexts":["worldcup"]},
  {"name":"Gheorghe Hagi","display_name":"Gheorghe Hagi","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Gheorghe_Hagi_2014.jpg/500px-Gheorghe_Hagi_2014.jpg","nationality":"Roumanie","position":"Milieu offensif","goat_positions":["midfielders"],"era":"années 1980-2000","clubs":["Steaua Bucarest","Real Madrid","Brescia","FC Barcelone","Galatasaray"],"national_team":"Roumanie","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":[],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":[],"fifa_awards":[],"major_records":["Plus grande icône du football roumain","Héros de Galatasaray"],"iconic_moments":["Coupe du Monde 1994","Galatasaray Coupe UEFA 2000","Real/Barça"],"nickname":"Maradona des Carpates","legacy":"Meneur flamboyant, pied gauche magique et figure nationale roumaine.","playing_style":"Passe, frappe, dribble, vision et coups de génie.","why_legend":"Il a porté la Roumanie à son plus haut niveau moderne et marqué plusieurs grands clubs.","goat_score":84,"hall_of_fame_tier":"A","contexts":["worldcup","euro"]},
  {"name":"Pavel Nedvěd","display_name":"Pavel Nedvěd","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Pavel_Nedved_2014.jpg/500px-Pavel_Nedved_2014.jpg","nationality":"Tchéquie","position":"Milieu","goat_positions":["midfielders"],"era":"années 1990-2000","clubs":["Sparta Prague","Lazio","Juventus"],"national_team":"Tchéquie","ballon_dor_count":1,"ballon_dor_years":["2003"],"world_cup_titles":[],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":[],"fifa_awards":[],"major_records":["Ballon d'Or 2003","Icône de la Juventus"],"iconic_moments":["Euro 1996","Juventus début 2000","Ballon d'Or 2003"],"nickname":"Furia Ceca","legacy":"Milieu énergique, technique et combattant, référence tchèque moderne.","playing_style":"Volume, frappe, percussion, passes et combativité.","why_legend":"Ballon d'Or et leader d'une grande génération tchèque.","goat_score":84,"hall_of_fame_tier":"A","contexts":["worldcup","euro","champions"]},
  {"name":"Luís Figo","display_name":"Luís Figo","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Luis_Figo_2017.jpg/500px-Luis_Figo_2017.jpg","nationality":"Portugal","position":"Ailier / milieu","goat_positions":["attackers","midfielders"],"era":"années 1990-2000","clubs":["Sporting CP","FC Barcelone","Real Madrid","Inter"],"national_team":"Portugal","ballon_dor_count":1,"ballon_dor_years":["2000"],"world_cup_titles":[],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":["2002"],"fifa_awards":["FIFA World Player 2001"],"major_records":["Ballon d'Or 2000","Figure des Galactiques"],"iconic_moments":["Transfert Barça-Real","Ligue des Champions 2002","génération dorée portugaise"],"nickname":"Figo","legacy":"Ailier technique majeur, figure centrale du Portugal moderne avant Cristiano.","playing_style":"Dribble, centres, conservation, un contre un et passe.","why_legend":"Ballon d'Or, Galactique et leader portugais au tournant des années 2000.","goat_score":86,"hall_of_fame_tier":"A+","contexts":["worldcup","euro","champions"]},

  {"name":"Marco van Basten","display_name":"Marco van Basten","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Marco_van_Basten_1988.jpg/500px-Marco_van_Basten_1988.jpg","nationality":"Pays-Bas","position":"Attaquant","goat_positions":["attackers"],"era":"années 1980-1990","clubs":["Ajax","AC Milan"],"national_team":"Pays-Bas","ballon_dor_count":3,"ballon_dor_years":["1988","1989","1992"],"world_cup_titles":[],"euro_titles":["1988"],"copa_america_titles":[],"champions_league_titles":["1989","1990"],"fifa_awards":["FIFA World Player 1992"],"major_records":["Triple Ballon d'Or","Volée mythique en finale Euro 1988"],"iconic_moments":["Euro 1988","AC Milan Sacchi","Ballon d'Or 1992"],"nickname":"San Marco","legacy":"Avant-centre d'une élégance rare, pic de niveau immense malgré une carrière écourtée.","playing_style":"Finition, jeu aérien, volées, appels, technique d'avant-centre.","why_legend":"Trois Ballons d'Or, Euro et Milan européen : un des pics offensifs les plus purs.","goat_score":94,"hall_of_fame_tier":"S","contexts":["euro","champions"]},
  {"name":"Gerd Müller","display_name":"Gerd Müller","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Gerd_Mueller_1974.jpg/500px-Gerd_Mueller_1974.jpg","nationality":"Allemagne","position":"Attaquant","goat_positions":["attackers"],"era":"années 1960-1970","clubs":["Bayern Munich","Fort Lauderdale Strikers"],"national_team":"Allemagne","ballon_dor_count":1,"ballon_dor_years":["1970"],"world_cup_titles":["1974"],"euro_titles":["1972"],"copa_america_titles":[],"champions_league_titles":["1974","1975","1976"],"fifa_awards":[],"major_records":["Un des plus grands buteurs de l'histoire","Buteur de la finale Mondial 1974"],"iconic_moments":["Coupe du Monde 1974","Euro 1972","Bayern triple champion d'Europe"],"nickname":"Der Bomber","legacy":"Référence absolue du finisseur dans la surface.","playing_style":"Instinct, finition rapide, déplacements courts, sens du but.","why_legend":"Un rendement de buteur exceptionnel et un palmarès complet club/sélection.","goat_score":93,"hall_of_fame_tier":"S","contexts":["worldcup","euro","champions"]},
  {"name":"Kenny Dalglish","display_name":"Kenny Dalglish","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Kenny_Dalglish_2011.jpg/500px-Kenny_Dalglish_2011.jpg","nationality":"Écosse","position":"Attaquant","goat_positions":["attackers"],"era":"années 1970-1980","clubs":["Celtic","Liverpool"],"national_team":"Écosse","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":[],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":["1978","1981","1984"],"fifa_awards":[],"major_records":["Icône de Liverpool","Triple champion d'Europe"],"iconic_moments":["Liverpool européen","années Paisley/Fagan","Celtic"],"nickname":"King Kenny","legacy":"Légende de Liverpool, attaquant intelligent et créateur.","playing_style":"Attaquant-meneur, déplacements, passes, finition et intelligence.","why_legend":"Il incarne l'âge d'or européen de Liverpool et reste une figure immense du club.","goat_score":88,"hall_of_fame_tier":"A+","contexts":["worldcup","champions"]},
  {"name":"Didier Drogba","display_name":"Didier Drogba","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Didier_Drogba_2019.jpg/500px-Didier_Drogba_2019.jpg","nationality":"Côte d'Ivoire","position":"Attaquant","goat_positions":["attackers"],"era":"années 2000-2010","clubs":["Le Mans","Guingamp","Marseille","Chelsea","Galatasaray"],"national_team":"Côte d'Ivoire","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":[],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":["2012"],"fifa_awards":[],"major_records":["Héros de Chelsea 2012","Icône du football africain"],"iconic_moments":["Finale Ligue des Champions 2012","Chelsea Mourinho","Marseille 2004"],"nickname":"Didi","legacy":"Avant-centre de grands matchs, puissance et leadership émotionnel.","playing_style":"Pivot, puissance, jeu aérien, coups francs, finition clutch.","why_legend":"Son égalisation et son tir au but en 2012 ont changé l'histoire de Chelsea.","goat_score":85,"hall_of_fame_tier":"A+","contexts":["worldcup","champions"]},
  {"name":"Samuel Eto'o","display_name":"Samuel Eto'o","photo_url":"https://images.fotmob.com/image_resources/playerimages/33639.png","nationality":"Cameroun","position":"Attaquant","goat_positions":["attackers"],"era":"années 2000-2010","clubs":["Mallorca","FC Barcelone","Inter","Chelsea","Anzhi","Sampdoria"],"national_team":"Cameroun","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":[],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":["2006","2009","2010"],"fifa_awards":["Joueur africain de l'année"],"major_records":["Deux triplés européens consécutifs avec deux clubs","Légende africaine"],"iconic_moments":["Barça 2006 et 2009","Inter 2010","CAN avec le Cameroun"],"nickname":"Samuel","legacy":"Un des plus grands attaquants africains, rapide, tueur et décisif en finale.","playing_style":"Appels, vitesse, finition, pressing et efficacité en grands matchs.","why_legend":"Trois Ligues des Champions et une place majeure dans l'histoire du football africain.","goat_score":88,"hall_of_fame_tier":"A+","contexts":["worldcup","champions"]},
  {"name":"Gabriel Batistuta","display_name":"Gabriel Batistuta","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Gabriel_Batistuta_2014.jpg/500px-Gabriel_Batistuta_2014.jpg","nationality":"Argentine","position":"Attaquant","goat_positions":["attackers"],"era":"années 1990-2000","clubs":["Boca Juniors","Fiorentina","Roma","Inter"],"national_team":"Argentine","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":[],"euro_titles":[],"copa_america_titles":["1991","1993"],"champions_league_titles":[],"fifa_awards":[],"major_records":["Un des grands buteurs argentins","Icône de la Fiorentina"],"iconic_moments":["Fiorentina années 1990","Roma championne 2001","Copa América"],"nickname":"Batigol","legacy":"Avant-centre puissant et clinique, idole absolue de Florence.","playing_style":"Frappe lourde, finition, appels, jeu aérien et puissance.","why_legend":"Sa force de frappe et son aura de buteur ont marqué la Serie A et l'Argentine.","goat_score":84,"hall_of_fame_tier":"A","contexts":["worldcup"]},
  {"name":"Paolo Rossi","display_name":"Paolo Rossi","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Paolo_Rossi_1982.jpg/500px-Paolo_Rossi_1982.jpg","nationality":"Italie","position":"Attaquant","goat_positions":["attackers"],"era":"années 1970-1980","clubs":["Vicenza","Juventus","AC Milan"],"national_team":"Italie","ballon_dor_count":1,"ballon_dor_years":["1982"],"world_cup_titles":["1982"],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":["1985"],"fifa_awards":["Soulier d'or Coupe du Monde 1982"],"major_records":["Héros de la Coupe du Monde 1982","Ballon d'Or 1982"],"iconic_moments":["Triplé contre le Brésil 1982","finale Mondial 1982","Juventus"],"nickname":"Pablito","legacy":"Buteur opportuniste devenu héros national italien en 1982.","playing_style":"Renard des surfaces, timing, appels courts et finition.","why_legend":"Son Mondial 1982 reste une des plus grandes renaissances individuelles du football.","goat_score":86,"hall_of_fame_tier":"A+","contexts":["worldcup","champions"]},
  {"name":"Andriy Shevchenko","display_name":"Andriy Shevchenko","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Andriy_Shevchenko_2017.jpg/500px-Andriy_Shevchenko_2017.jpg","nationality":"Ukraine","position":"Attaquant","goat_positions":["attackers"],"era":"années 1990-2000","clubs":["Dynamo Kyiv","AC Milan","Chelsea"],"national_team":"Ukraine","ballon_dor_count":1,"ballon_dor_years":["2004"],"world_cup_titles":[],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":["2003"],"fifa_awards":[],"major_records":["Ballon d'Or 2004","Légende du Milan et de l'Ukraine"],"iconic_moments":["Ligue des Champions 2003","Dynamo Kyiv","Milan Ancelotti"],"nickname":"Sheva","legacy":"Attaquant complet, symbole ukrainien et buteur européen majeur.","playing_style":"Finition, vitesse, appels, frappe, jeu aérien.","why_legend":"Ballon d'Or, champion d'Europe et icône nationale ukrainienne.","goat_score":86,"hall_of_fame_tier":"A+","contexts":["worldcup","euro","champions"]},
  {"name":"Robert Lewandowski","display_name":"Robert Lewandowski","photo_url":"https://images.fotmob.com/image_resources/playerimages/41689.png","nationality":"Pologne","position":"Attaquant","goat_positions":["attackers"],"era":"années 2010-2020","clubs":["Lech Poznań","Borussia Dortmund","Bayern Munich","FC Barcelone"],"national_team":"Pologne","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":[],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":["2020"],"fifa_awards":["The Best FIFA 2020 et 2021"],"major_records":["Buteur historique du Bayern moderne","Saison 2020 dominante"],"iconic_moments":["Quintuplé en 9 minutes","Ligue des Champions 2020","records Bundesliga"],"nickname":"Lewy","legacy":"Un des plus grands numéros 9 modernes par son rendement et sa technique de finition.","playing_style":"Avant-centre complet, finition, jeu dos au but, appels, technique.","why_legend":"Son rendement au Bayern et sa saison 2020 l'ont placé parmi les grands buteurs historiques.","goat_score":89,"hall_of_fame_tier":"S","contexts":["worldcup","euro","champions"]},
  {"name":"Zlatan Ibrahimović","display_name":"Zlatan Ibrahimović","photo_url":"https://images.fotmob.com/image_resources/playerimages/3455.png","nationality":"Suède","position":"Attaquant","goat_positions":["attackers"],"era":"années 2000-2020","clubs":["Ajax","Juventus","Inter","FC Barcelone","AC Milan","PSG","Manchester United","LA Galaxy"],"national_team":"Suède","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":[],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":[],"fifa_awards":["Prix Puskás 2013"],"major_records":["Buteur majeur de nombreux championnats","Icône du PSG moderne"],"iconic_moments":["But retourné contre l'Angleterre","PSG champion","Milan et Inter"],"nickname":"Ibra","legacy":"Attaquant charismatique, spectaculaire et dominant physiquement.","playing_style":"Pivot technique, gestes acrobatiques, puissance, finition et personnalité.","why_legend":"Il a marqué partout, imposé son style et construit une aura unique.","goat_score":84,"hall_of_fame_tier":"A","contexts":["euro","champions"]},
  {"name":"Luis Suárez","display_name":"Luis Suárez","photo_url":"https://images.fotmob.com/image_resources/playerimages/9760.png","nationality":"Uruguay","position":"Attaquant","goat_positions":["attackers"],"era":"années 2010-2020","clubs":["Ajax","Liverpool","FC Barcelone","Atlético Madrid","Inter Miami"],"national_team":"Uruguay","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":[],"euro_titles":[],"copa_america_titles":["2011"],"champions_league_titles":["2015"],"fifa_awards":[],"major_records":["Soulier d'or européen hors duo Messi/Ronaldo","Membre du trio MSN"],"iconic_moments":["Barça 2015","Liverpool 2013-2014","Copa América 2011"],"nickname":"El Pistolero","legacy":"Avant-centre agressif, imprévisible, buteur et créateur d'élite.","playing_style":"Finition, pressing, dribble court, instinct, passes et combativité.","why_legend":"Il a rivalisé statistiquement avec Messi/Ronaldo et formé un trio mythique au Barça.","goat_score":86,"hall_of_fame_tier":"A+","contexts":["worldcup","champions"]},
  {"name":"Karim Benzema","display_name":"Karim Benzema","photo_url":"https://images.fotmob.com/image_resources/playerimages/32344.png","nationality":"France","position":"Attaquant","goat_positions":["attackers"],"era":"années 2000-2020","clubs":["Lyon","Real Madrid","Al Ittihad"],"national_team":"France","ballon_dor_count":1,"ballon_dor_years":["2022"],"world_cup_titles":[],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":["2014","2016","2017","2018","2022"],"fifa_awards":[],"major_records":["Ballon d'Or 2022","Leader du Real Madrid champion d'Europe 2022"],"iconic_moments":["Campagne Champions 2022","trio BBC","Real Madrid"],"nickname":"KB9","legacy":"Avant-centre complet, lien du jeu et buteur décisif au Real Madrid.","playing_style":"Décrochage, combinaison, finition, jeu dos au but, intelligence.","why_legend":"Cinq Ligues des Champions et une saison Ballon d'Or avec un impact majeur.","goat_score":88,"hall_of_fame_tier":"A+","contexts":["euro","champions"]},
  {"name":"Raúl","display_name":"Raúl","photo_url":"https://images.fotmob.com/image_resources/playerimages/7452.png","nationality":"Espagne","position":"Attaquant","goat_positions":["attackers"],"era":"années 1990-2000","clubs":["Real Madrid","Schalke 04","Al Sadd","New York Cosmos"],"national_team":"Espagne","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":[],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":["1998","2000","2002"],"fifa_awards":[],"major_records":["Buteur historique du Real Madrid avant Ronaldo","Icône de la Ligue des Champions"],"iconic_moments":["Real Madrid 1998-2002","buts en C1","capitaine madrilène"],"nickname":"El Ángel de Madrid","legacy":"Symbole du Real Madrid, intelligence d'appel et finition sobre.","playing_style":"Appels, finition, sens collectif, déplacement et leadership.","why_legend":"Triple champion d'Europe et visage du Real Madrid avant l'ère Galactiques tardive.","goat_score":85,"hall_of_fame_tier":"A+","contexts":["worldcup","euro","champions"]},
  {"name":"Mohamed Salah","display_name":"Mohamed Salah","photo_url":"https://images.fotmob.com/image_resources/playerimages/292462.png","nationality":"Égypte","position":"Attaquant","goat_positions":["attackers"],"era":"années 2010-2020","clubs":["Basel","Chelsea","Fiorentina","Roma","Liverpool"],"national_team":"Égypte","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":[],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":["2019"],"fifa_awards":["Prix Puskás 2018"],"major_records":["Icône africaine de Premier League","Buteur historique moderne de Liverpool"],"iconic_moments":["Ligue des Champions 2019","Premier League 2020","records avec Liverpool"],"nickname":"Mo Salah","legacy":"Ailier-buteur d'élite, symbole de Liverpool Klopp et du football égyptien.","playing_style":"Appels diagonaux, finition pied gauche, vitesse, pressing.","why_legend":"Il a transformé Liverpool et porté le football égyptien au sommet médiatique mondial.","goat_score":84,"hall_of_fame_tier":"A","contexts":["worldcup","champions"]},
  {"name":"Sadio Mané","display_name":"Sadio Mané","photo_url":"https://images.fotmob.com/image_resources/playerimages/292453.png","nationality":"Sénégal","position":"Attaquant","goat_positions":["attackers"],"era":"années 2010-2020","clubs":["Metz","Red Bull Salzburg","Southampton","Liverpool","Bayern Munich","Al Nassr"],"national_team":"Sénégal","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":[],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":["2019"],"fifa_awards":[],"major_records":["Vainqueur CAN 2021","Figure majeure de Liverpool Klopp"],"iconic_moments":["CAN 2021","Ligue des Champions 2019","Premier League 2020"],"nickname":"Sadio","legacy":"Attaquant généreux, rapide, décisif et icône du Sénégal.","playing_style":"Vitesse, pressing, appels, finition et intensité.","why_legend":"Champion d'Afrique, champion d'Europe et visage d'une grande génération sénégalaise.","goat_score":82,"hall_of_fame_tier":"A","contexts":["worldcup","champions"]},
  {"name":"Wayne Rooney","display_name":"Wayne Rooney","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Wayne_Rooney_2018.jpg/500px-Wayne_Rooney_2018.jpg","nationality":"Angleterre","position":"Attaquant","goat_positions":["attackers"],"era":"années 2000-2010","clubs":["Everton","Manchester United","D.C. United","Derby County"],"national_team":"Angleterre","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":[],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":["2008"],"fifa_awards":[],"major_records":["Buteur historique de Manchester United pendant longtemps","Icône anglaise moderne"],"iconic_moments":["Retourné contre Manchester City","Ligue des Champions 2008","Euro 2004"],"nickname":"Wazza","legacy":"Attaquant complet, intense, créatif et buteur, symbole de Manchester United.","playing_style":"Puissance, frappe, passe, pressing, créativité et engagement.","why_legend":"Il a porté Manchester United et l'Angleterre par son talent précoce et sa polyvalence.","goat_score":83,"hall_of_fame_tier":"A","contexts":["worldcup","euro","champions"]},
  {"name":"George Weah","display_name":"George Weah","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/George_Weah_2019.jpg/500px-George_Weah_2019.jpg","nationality":"Liberia","position":"Attaquant","goat_positions":["attackers"],"era":"années 1990","clubs":["Monaco","PSG","AC Milan","Chelsea","Manchester City","Marseille"],"national_team":"Liberia","ballon_dor_count":1,"ballon_dor_years":["1995"],"world_cup_titles":[],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":[],"fifa_awards":["FIFA World Player 1995"],"major_records":["Seul Africain Ballon d'Or","Icône du football libérien"],"iconic_moments":["Ballon d'Or 1995","AC Milan","PSG/Monaco"],"nickname":"Mister George","legacy":"Symbole africain mondial, puissance et élégance en attaque.","playing_style":"Vitesse, puissance, dribble, finition et courses longues.","why_legend":"Son Ballon d'Or 1995 reste un marqueur historique pour le football africain.","goat_score":87,"hall_of_fame_tier":"A+","contexts":["champions"]},
  {"name":"Hristo Stoichkov","display_name":"Hristo Stoichkov","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Hristo_Stoichkov_2016.jpg/500px-Hristo_Stoichkov_2016.jpg","nationality":"Bulgarie","position":"Attaquant","goat_positions":["attackers"],"era":"années 1990","clubs":["CSKA Sofia","FC Barcelone","Parma","Chicago Fire"],"national_team":"Bulgarie","ballon_dor_count":1,"ballon_dor_years":["1994"],"world_cup_titles":[],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":["1992"],"fifa_awards":[],"major_records":["Ballon d'Or 1994","Soulier d'or de la Coupe du Monde 1994","Icône de la Dream Team du Barça"],"iconic_moments":["Coupe du Monde 1994","Ligue des Champions 1992","Dream Team de Johan Cruyff"],"nickname":"El Pistolero","legacy":"Attaquant de caractère, symbole de la Bulgarie et du Barça des années 1990.","playing_style":"Pied gauche violent, appels, agressivité, frappe et créativité.","why_legend":"Ballon d'Or, héros national bulgare et joueur majeur du Barça de Cruyff.","goat_score":86,"hall_of_fame_tier":"A+","contexts":["worldcup","euro","champions"]},
  {"name":"Hugo Sánchez","display_name":"Hugo Sánchez","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Hugo_S%C3%A1nchez_2016.jpg/500px-Hugo_S%C3%A1nchez_2016.jpg","nationality":"Mexique","position":"Attaquant","goat_positions":["attackers"],"era":"années 1980-1990","clubs":["Pumas UNAM","Atlético Madrid","Real Madrid","Rayo Vallecano"],"national_team":"Mexique","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":[],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":[],"fifa_awards":[],"major_records":["Quintuple Pichichi","Un des plus grands buteurs de l'histoire de la Liga","Icône du football mexicain"],"iconic_moments":["Real Madrid de la Quinta del Buitre","saisons Pichichi","Coupe du Monde avec le Mexique"],"nickname":"Hugol","legacy":"Buteur acrobatique et clinique, référence mexicaine absolue en Europe.","playing_style":"Finition instinctive, retournés, déplacements de renard et jeu aérien.","why_legend":"Dominant en Liga avec le Real Madrid, il a porté le football mexicain au sommet européen.","goat_score":85,"hall_of_fame_tier":"A+","contexts":["worldcup"]},
  {"name":"Roger Milla","display_name":"Roger Milla","photo_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Roger_Milla_2010.jpg/500px-Roger_Milla_2010.jpg","nationality":"Cameroun","position":"Attaquant","goat_positions":["attackers"],"era":"années 1970-1990","clubs":["Valenciennes","Monaco","Bastia","Saint-Étienne","Montpellier","Tonnerre Yaoundé"],"national_team":"Cameroun","ballon_dor_count":0,"ballon_dor_years":[],"world_cup_titles":[],"euro_titles":[],"copa_america_titles":[],"champions_league_titles":[],"fifa_awards":[],"major_records":["Icône africaine de la Coupe du Monde 1990","Plus vieux buteur de l'histoire de la Coupe du Monde pendant longtemps"],"iconic_moments":["Danse du poteau de corner en 1990","Cameroun quart de finaliste 1990","but à 42 ans en 1994"],"nickname":"Le Vieux Lion","legacy":"Figure majeure du football africain, associé à l'épopée camerounaise de 1990.","playing_style":"Instinct, malice, finition, jeu dos au but et sens du spectacle.","why_legend":"Il a donné une visibilité mondiale au football africain par ses buts et son charisme.","goat_score":84,"hall_of_fame_tier":"A","contexts":["worldcup"]}
]$hof100$::jsonb) as x(
    name text, display_name text, photo_url text, nationality text, position text, goat_positions jsonb,
    era text, clubs jsonb, national_team text, ballon_dor_count int, ballon_dor_years jsonb,
    world_cup_titles jsonb, euro_titles jsonb, copa_america_titles jsonb, champions_league_titles jsonb,
    fifa_awards jsonb, major_records jsonb, iconic_moments jsonb, nickname text, legacy text,
    playing_style text, why_legend text, goat_score numeric, hall_of_fame_tier text, contexts jsonb
  )
),
seed_with_player as (
  select
    s.*,
    (
      select p.id
      from public.players p
      where lower(p.name) in (lower(s.name), lower(s.display_name))
      order by p.updated_at desc nulls last
      limit 1
    ) as player_id
  from seed s
)
insert into public.hall_of_fame_players (
  player_id, name, display_name, photo_url, nationality, position, era, clubs, national_team,
  ballon_dor_count, ballon_dor_years, world_cup_titles, euro_titles, copa_america_titles,
  champions_league_titles, fifa_awards, major_records, iconic_moments, nickname, legacy,
  playing_style, why_legend, goat_score, hall_of_fame_tier, source, last_enriched_at
)
select
  player_id, name, display_name, photo_url, nationality, position, era, clubs, national_team,
  ballon_dor_count, ballon_dor_years, world_cup_titles, euro_titles, copa_america_titles,
  champions_league_titles, fifa_awards, major_records, iconic_moments, nickname, legacy,
  playing_style, why_legend, goat_score, hall_of_fame_tier, 'akro-curated-v2-hof100', now()
from seed_with_player
on conflict (name) do update set
  player_id = coalesce(excluded.player_id, public.hall_of_fame_players.player_id),
  display_name = coalesce(nullif(excluded.display_name, ''), public.hall_of_fame_players.display_name),
  photo_url = coalesce(nullif(excluded.photo_url, ''), public.hall_of_fame_players.photo_url),
  nationality = coalesce(nullif(excluded.nationality, ''), public.hall_of_fame_players.nationality),
  position = coalesce(nullif(excluded.position, ''), public.hall_of_fame_players.position),
  era = coalesce(nullif(excluded.era, ''), public.hall_of_fame_players.era),
  clubs = case when jsonb_array_length(excluded.clubs) > 0 then excluded.clubs else public.hall_of_fame_players.clubs end,
  national_team = coalesce(nullif(excluded.national_team, ''), public.hall_of_fame_players.national_team),
  ballon_dor_count = greatest(public.hall_of_fame_players.ballon_dor_count, excluded.ballon_dor_count),
  ballon_dor_years = case when jsonb_array_length(excluded.ballon_dor_years) > 0 then excluded.ballon_dor_years else public.hall_of_fame_players.ballon_dor_years end,
  world_cup_titles = case when jsonb_array_length(excluded.world_cup_titles) > 0 then excluded.world_cup_titles else public.hall_of_fame_players.world_cup_titles end,
  euro_titles = case when jsonb_array_length(excluded.euro_titles) > 0 then excluded.euro_titles else public.hall_of_fame_players.euro_titles end,
  copa_america_titles = case when jsonb_array_length(excluded.copa_america_titles) > 0 then excluded.copa_america_titles else public.hall_of_fame_players.copa_america_titles end,
  champions_league_titles = case when jsonb_array_length(excluded.champions_league_titles) > 0 then excluded.champions_league_titles else public.hall_of_fame_players.champions_league_titles end,
  fifa_awards = case when jsonb_array_length(excluded.fifa_awards) > 0 then excluded.fifa_awards else public.hall_of_fame_players.fifa_awards end,
  major_records = case when jsonb_array_length(excluded.major_records) > 0 then excluded.major_records else public.hall_of_fame_players.major_records end,
  iconic_moments = case when jsonb_array_length(excluded.iconic_moments) > 0 then excluded.iconic_moments else public.hall_of_fame_players.iconic_moments end,
  nickname = coalesce(nullif(excluded.nickname, ''), public.hall_of_fame_players.nickname),
  legacy = coalesce(nullif(excluded.legacy, ''), public.hall_of_fame_players.legacy),
  playing_style = coalesce(nullif(excluded.playing_style, ''), public.hall_of_fame_players.playing_style),
  why_legend = coalesce(nullif(excluded.why_legend, ''), public.hall_of_fame_players.why_legend),
  goat_score = greatest(coalesce(public.hall_of_fame_players.goat_score, 0), coalesce(excluded.goat_score, 0)),
  hall_of_fame_tier = coalesce(nullif(excluded.hall_of_fame_tier, ''), public.hall_of_fame_players.hall_of_fame_tier),
  source = case when public.hall_of_fame_players.source = 'akro-curated-v1' then public.hall_of_fame_players.source else 'akro-curated-v2-hof100' end,
  last_enriched_at = now(),
  updated_at = now();

with hof as (
  select h.*, s.goat_positions, s.contexts
  from public.hall_of_fame_players h
  join (
    select *
    from jsonb_to_recordset($tags100$
[
  {"name":"Dino Zoff","goat_positions":["goalkeepers"],"contexts":["worldcup","euro"],"clubs":["Udinese","Mantova","Napoli","Juventus"],"nation":"Italie","era":"années 1960-1980"},
  {"name":"Iker Casillas","goat_positions":["goalkeepers"],"contexts":["worldcup","euro","champions"],"clubs":["Real Madrid","Porto"],"nation":"Espagne","era":"années 2000-2010"},
  {"name":"Manuel Neuer","goat_positions":["goalkeepers"],"contexts":["worldcup","euro","champions"],"clubs":["Schalke 04","Bayern Munich"],"nation":"Allemagne","era":"années 2010-2020"},
  {"name":"Peter Schmeichel","goat_positions":["goalkeepers"],"contexts":["euro","champions"],"clubs":["Brøndby","Manchester United","Sporting CP","Aston Villa","Manchester City"],"nation":"Danemark","era":"années 1990"},
  {"name":"Oliver Kahn","goat_positions":["goalkeepers"],"contexts":["worldcup","euro","champions"],"clubs":["Karlsruher SC","Bayern Munich"],"nation":"Allemagne","era":"années 1990-2000"},
  {"name":"Sepp Maier","goat_positions":["goalkeepers"],"contexts":["worldcup","euro","champions"],"clubs":["Bayern Munich"],"nation":"Allemagne","era":"années 1960-1970"},
  {"name":"Gordon Banks","goat_positions":["goalkeepers"],"contexts":["worldcup"],"clubs":["Leicester City","Stoke City"],"nation":"Angleterre","era":"années 1960-1970"},
  {"name":"Edwin van der Sar","goat_positions":["goalkeepers"],"contexts":["euro","champions"],"clubs":["Ajax","Juventus","Fulham","Manchester United"],"nation":"Pays-Bas","era":"années 1990-2010"},
  {"name":"José Luis Chilavert","goat_positions":["goalkeepers"],"contexts":["worldcup"],"clubs":["Vélez Sarsfield","Strasbourg","Peñarol"],"nation":"Paraguay","era":"années 1990-2000"},
  {"name":"Dida","goat_positions":["goalkeepers"],"contexts":["worldcup","champions"],"clubs":["Cruzeiro","Corinthians","AC Milan"],"nation":"Brésil","era":"années 1990-2000"},
  {"name":"René Higuita","goat_positions":["goalkeepers"],"contexts":["worldcup"],"clubs":["Atlético Nacional","Real Valladolid"],"nation":"Colombie","era":"années 1980-1990"},
  {"name":"Emiliano Martínez","goat_positions":["goalkeepers"],"contexts":["worldcup"],"clubs":["Arsenal","Aston Villa"],"nation":"Argentine","era":"années 2020"},
  {"name":"Franco Baresi","goat_positions":["defenders"],"contexts":["worldcup","euro","champions"],"clubs":["AC Milan"],"nation":"Italie","era":"années 1980-1990"},
  {"name":"Roberto Carlos","goat_positions":["defenders"],"contexts":["worldcup","champions"],"clubs":["Palmeiras","Inter","Real Madrid","Fenerbahçe"],"nation":"Brésil","era":"années 1990-2000"},
  {"name":"Cafu","goat_positions":["defenders"],"contexts":["worldcup","champions"],"clubs":["São Paulo","Roma","AC Milan"],"nation":"Brésil","era":"années 1990-2000"},
  {"name":"Fabio Cannavaro","goat_positions":["defenders"],"contexts":["worldcup","euro","champions"],"clubs":["Napoli","Parma","Inter","Juventus","Real Madrid"],"nation":"Italie","era":"années 1990-2000"},
  {"name":"Marcel Desailly","goat_positions":["defenders"],"contexts":["worldcup","euro","champions"],"clubs":["Nantes","Marseille","AC Milan","Chelsea"],"nation":"France","era":"années 1990-2000"},
  {"name":"Bobby Moore","goat_positions":["defenders"],"contexts":["worldcup"],"clubs":["West Ham United","Fulham"],"nation":"Angleterre","era":"années 1960-1970"},
  {"name":"Carlos Alberto","goat_positions":["defenders"],"contexts":["worldcup"],"clubs":["Fluminense","Santos","New York Cosmos"],"nation":"Brésil","era":"années 1960-1970"},
  {"name":"Daniel Passarella","goat_positions":["defenders"],"contexts":["worldcup"],"clubs":["River Plate","Fiorentina","Inter"],"nation":"Argentine","era":"années 1970-1980"},
  {"name":"Carles Puyol","goat_positions":["defenders"],"contexts":["worldcup","euro","champions"],"clubs":["FC Barcelone"],"nation":"Espagne","era":"années 2000-2010"},
  {"name":"Philipp Lahm","goat_positions":["defenders","midfielders"],"contexts":["worldcup","euro","champions"],"clubs":["Bayern Munich","VfB Stuttgart"],"nation":"Allemagne","era":"années 2000-2010"},
  {"name":"Gerard Piqué","goat_positions":["defenders"],"contexts":["worldcup","euro","champions"],"clubs":["Manchester United","FC Barcelone"],"nation":"Espagne","era":"années 2000-2020"},
  {"name":"Alessandro Nesta","goat_positions":["defenders"],"contexts":["worldcup","euro","champions"],"clubs":["Lazio","AC Milan"],"nation":"Italie","era":"années 1990-2000"},
  {"name":"Gaetano Scirea","goat_positions":["defenders"],"contexts":["worldcup","champions"],"clubs":["Atalanta","Juventus"],"nation":"Italie","era":"années 1970-1980"},
  {"name":"Nilton Santos","goat_positions":["defenders"],"contexts":["worldcup"],"clubs":["Botafogo"],"nation":"Brésil","era":"années 1950-1960"},
  {"name":"Dani Alves","goat_positions":["defenders"],"contexts":["worldcup","champions"],"clubs":["Bahia","Sevilla","FC Barcelone","Juventus","PSG","São Paulo"],"nation":"Brésil","era":"années 2000-2020"},
  {"name":"Javier Zanetti","goat_positions":["defenders","midfielders"],"contexts":["worldcup","champions"],"clubs":["Banfield","Inter"],"nation":"Argentine","era":"années 1990-2010"},
  {"name":"Lilian Thuram","goat_positions":["defenders"],"contexts":["worldcup","euro","champions"],"clubs":["Monaco","Parma","Juventus","FC Barcelone"],"nation":"France","era":"années 1990-2000"},
  {"name":"Ashley Cole","goat_positions":["defenders"],"contexts":["worldcup","euro","champions"],"clubs":["Arsenal","Chelsea","Roma","LA Galaxy"],"nation":"Angleterre","era":"années 2000-2010"},
  {"name":"Andrea Pirlo","goat_positions":["midfielders"],"contexts":["worldcup","euro","champions"],"clubs":["Inter","AC Milan","Juventus","New York City FC"],"nation":"Italie","era":"années 2000-2010"},
  {"name":"Lothar Matthäus","goat_positions":["midfielders"],"contexts":["worldcup","euro","champions"],"clubs":["Borussia Mönchengladbach","Bayern Munich","Inter"],"nation":"Allemagne","era":"années 1980-1990"},
  {"name":"Ruud Gullit","goat_positions":["midfielders","attackers"],"contexts":["euro","champions"],"clubs":["Feyenoord","PSV","AC Milan","Chelsea"],"nation":"Pays-Bas","era":"années 1980-1990"},
  {"name":"Zico","goat_positions":["midfielders"],"contexts":["worldcup"],"clubs":["Flamengo","Udinese","Kashima Antlers"],"nation":"Brésil","era":"années 1970-1980"},
  {"name":"Sócrates","goat_positions":["midfielders"],"contexts":["worldcup"],"clubs":["Botafogo-SP","Corinthians","Fiorentina","Flamengo","Santos"],"nation":"Brésil","era":"années 1970-1980"},
  {"name":"Frank Rijkaard","goat_positions":["midfielders","defenders"],"contexts":["euro","champions"],"clubs":["Ajax","AC Milan"],"nation":"Pays-Bas","era":"années 1980-1990"},
  {"name":"Clarence Seedorf","goat_positions":["midfielders"],"contexts":["worldcup","euro","champions"],"clubs":["Ajax","Real Madrid","Inter","AC Milan","Botafogo"],"nation":"Pays-Bas","era":"années 1990-2010"},
  {"name":"Michael Laudrup","goat_positions":["midfielders"],"contexts":["worldcup","euro","champions"],"clubs":["Juventus","FC Barcelone","Real Madrid","Ajax"],"nation":"Danemark","era":"années 1980-1990"},
  {"name":"Dennis Bergkamp","goat_positions":["attackers","midfielders"],"contexts":["worldcup","euro","champions"],"clubs":["Ajax","Inter","Arsenal"],"nation":"Pays-Bas","era":"années 1990-2000"},
  {"name":"Patrick Vieira","goat_positions":["midfielders"],"contexts":["worldcup","euro","champions"],"clubs":["Cannes","AC Milan","Arsenal","Juventus","Inter","Manchester City"],"nation":"France","era":"années 1990-2000"},
  {"name":"Steven Gerrard","goat_positions":["midfielders"],"contexts":["worldcup","euro","champions"],"clubs":["Liverpool","LA Galaxy"],"nation":"Angleterre","era":"années 2000-2010"},
  {"name":"Paul Scholes","goat_positions":["midfielders"],"contexts":["worldcup","euro","champions"],"clubs":["Manchester United"],"nation":"Angleterre","era":"années 1990-2010"},
  {"name":"Frank Lampard","goat_positions":["midfielders"],"contexts":["worldcup","euro","champions"],"clubs":["West Ham United","Chelsea","Manchester City","New York City FC"],"nation":"Angleterre","era":"années 2000-2010"},
  {"name":"Toni Kroos","goat_positions":["midfielders"],"contexts":["worldcup","euro","champions"],"clubs":["Bayern Munich","Bayer Leverkusen","Real Madrid"],"nation":"Allemagne","era":"années 2010-2020"},
  {"name":"Kevin De Bruyne","goat_positions":["midfielders"],"contexts":["worldcup","euro","champions"],"clubs":["Genk","Chelsea","Wolfsburg","Manchester City"],"nation":"Belgique","era":"années 2010-2020"},
  {"name":"Roberto Rivelino","goat_positions":["midfielders"],"contexts":["worldcup"],"clubs":["Corinthians","Fluminense","Al Hilal"],"nation":"Brésil","era":"années 1960-1970"},
  {"name":"Didi","goat_positions":["midfielders"],"contexts":["worldcup"],"clubs":["Fluminense","Botafogo","Real Madrid"],"nation":"Brésil","era":"années 1950-1960"},
  {"name":"Gheorghe Hagi","goat_positions":["midfielders"],"contexts":["worldcup","euro"],"clubs":["Steaua Bucarest","Real Madrid","Brescia","FC Barcelone","Galatasaray"],"nation":"Roumanie","era":"années 1980-2000"},
  {"name":"Pavel Nedvěd","goat_positions":["midfielders"],"contexts":["worldcup","euro","champions"],"clubs":["Sparta Prague","Lazio","Juventus"],"nation":"Tchéquie","era":"années 1990-2000"},
  {"name":"Luís Figo","goat_positions":["attackers","midfielders"],"contexts":["worldcup","euro","champions"],"clubs":["Sporting CP","FC Barcelone","Real Madrid","Inter"],"nation":"Portugal","era":"années 1990-2000"},
  {"name":"Marco van Basten","goat_positions":["attackers"],"contexts":["euro","champions"],"clubs":["Ajax","AC Milan"],"nation":"Pays-Bas","era":"années 1980-1990"},
  {"name":"Gerd Müller","goat_positions":["attackers"],"contexts":["worldcup","euro","champions"],"clubs":["Bayern Munich","Fort Lauderdale Strikers"],"nation":"Allemagne","era":"années 1960-1970"},
  {"name":"Kenny Dalglish","goat_positions":["attackers"],"contexts":["worldcup","champions"],"clubs":["Celtic","Liverpool"],"nation":"Écosse","era":"années 1970-1980"},
  {"name":"Didier Drogba","goat_positions":["attackers"],"contexts":["worldcup","champions"],"clubs":["Le Mans","Guingamp","Marseille","Chelsea","Galatasaray"],"nation":"Côte d'Ivoire","era":"années 2000-2010"},
  {"name":"Samuel Eto'o","goat_positions":["attackers"],"contexts":["worldcup","champions"],"clubs":["Mallorca","FC Barcelone","Inter","Chelsea","Anzhi","Sampdoria"],"nation":"Cameroun","era":"années 2000-2010"},
  {"name":"Gabriel Batistuta","goat_positions":["attackers"],"contexts":["worldcup"],"clubs":["Boca Juniors","Fiorentina","Roma","Inter"],"nation":"Argentine","era":"années 1990-2000"},
  {"name":"Paolo Rossi","goat_positions":["attackers"],"contexts":["worldcup","champions"],"clubs":["Vicenza","Juventus","AC Milan"],"nation":"Italie","era":"années 1970-1980"},
  {"name":"Andriy Shevchenko","goat_positions":["attackers"],"contexts":["worldcup","euro","champions"],"clubs":["Dynamo Kyiv","AC Milan","Chelsea"],"nation":"Ukraine","era":"années 1990-2000"},
  {"name":"Robert Lewandowski","goat_positions":["attackers"],"contexts":["worldcup","euro","champions"],"clubs":["Lech Poznań","Borussia Dortmund","Bayern Munich","FC Barcelone"],"nation":"Pologne","era":"années 2010-2020"},
  {"name":"Zlatan Ibrahimović","goat_positions":["attackers"],"contexts":["euro","champions"],"clubs":["Ajax","Juventus","Inter","FC Barcelone","AC Milan","PSG","Manchester United","LA Galaxy"],"nation":"Suède","era":"années 2000-2020"},
  {"name":"Luis Suárez","goat_positions":["attackers"],"contexts":["worldcup","champions"],"clubs":["Ajax","Liverpool","FC Barcelone","Atlético Madrid","Inter Miami"],"nation":"Uruguay","era":"années 2010-2020"},
  {"name":"Karim Benzema","goat_positions":["attackers"],"contexts":["euro","champions"],"clubs":["Lyon","Real Madrid","Al Ittihad"],"nation":"France","era":"années 2000-2020"},
  {"name":"Raúl","goat_positions":["attackers"],"contexts":["worldcup","euro","champions"],"clubs":["Real Madrid","Schalke 04","Al Sadd","New York Cosmos"],"nation":"Espagne","era":"années 1990-2000"},
  {"name":"Mohamed Salah","goat_positions":["attackers"],"contexts":["worldcup","champions"],"clubs":["Basel","Chelsea","Fiorentina","Roma","Liverpool"],"nation":"Égypte","era":"années 2010-2020"},
  {"name":"Sadio Mané","goat_positions":["attackers"],"contexts":["worldcup","champions"],"clubs":["Metz","Red Bull Salzburg","Southampton","Liverpool","Bayern Munich","Al Nassr"],"nation":"Sénégal","era":"années 2010-2020"},
  {"name":"Wayne Rooney","goat_positions":["attackers"],"contexts":["worldcup","euro","champions"],"clubs":["Everton","Manchester United","D.C. United","Derby County"],"nation":"Angleterre","era":"années 2000-2010"},
  {"name":"George Weah","goat_positions":["attackers"],"contexts":["champions"],"clubs":["Monaco","PSG","AC Milan","Chelsea","Manchester City","Marseille"],"nation":"Liberia","era":"années 1990"},
  {"name":"Hristo Stoichkov","goat_positions":["attackers"],"contexts":["worldcup","euro","champions"],"clubs":["CSKA Sofia","FC Barcelone","Parma","Chicago Fire"],"nation":"Bulgarie","era":"années 1990"},
  {"name":"Hugo Sánchez","goat_positions":["attackers"],"contexts":["worldcup"],"clubs":["Pumas UNAM","Atlético Madrid","Real Madrid","Rayo Vallecano"],"nation":"Mexique","era":"années 1980-1990"},
  {"name":"Roger Milla","goat_positions":["attackers"],"contexts":["worldcup"],"clubs":["Valenciennes","Monaco","Bastia","Saint-Étienne","Montpellier","Tonnerre Yaoundé"],"nation":"Cameroun","era":"années 1970-1990"}
]$tags100$::jsonb) as x(name text, goat_positions jsonb, contexts jsonb, clubs jsonb, nation text, era text)
  ) s on s.name = h.name
),
tag_rows as (
  select player_id, name as player_name, 'nation' as tag_type, national_team as tag_value from hof
  union all
  select player_id, name, 'club', value #>> '{}' from hof cross join lateral jsonb_array_elements(clubs)
  union all
  select player_id, name, 'position', value #>> '{}' from hof cross join lateral jsonb_array_elements(goat_positions)
  union all
  select player_id, name, 'era', era from hof
  union all
  select player_id, name, value #>> '{}', value #>> '{}' from hof cross join lateral jsonb_array_elements(contexts)
)
insert into public.goat_player_tags (
  player_id, player_name, tag_type, tag_value, source, confidence, raw_data, updated_at
)
select
  player_id,
  player_name,
  tag_type,
  tag_value,
  'hall-of-fame-seed-v2',
  0.96,
  jsonb_build_object('seed', 'hall_of_fame_players', 'version', 'akro-curated-v2-hof100'),
  now()
from tag_rows
where coalesce(tag_value, '') <> ''
on conflict (player_name, tag_type, tag_value) do update set
  player_id = coalesce(excluded.player_id, public.goat_player_tags.player_id),
  source = excluded.source,
  confidence = greatest(coalesce(public.goat_player_tags.confidence, 0), excluded.confidence),
  raw_data = excluded.raw_data,
  updated_at = now();

insert into public.player_enrichment_logs (
  player_id, player_name, enrichment_type, source, status, message
)
select
  player_id,
  name,
  'hall_of_fame_seed_100',
  'akro-curated-v2-hof100',
  'success',
  'Vague Hall of Fame 100+ ajoutée et tags THE GOAT générés.'
from public.hall_of_fame_players
where source = 'akro-curated-v2-hof100';
