create table if not exists public.search_ai_answers (
  id bigint generated by default as identity primary key,
  query text not null,
  normalized_query text not null,
  answer text not null,
  created_at timestamptz not null default now(),
  usage_count integer not null default 1
);

create index if not exists idx_search_ai_answers_normalized_query
  on public.search_ai_answers (normalized_query);
